Repository LinumLabs/psydao-io, pull requests merged in 2024-11, with the labels that each got.

#227 add invalid deadline error message
  hooks/useCustomToasts.ts
Labels: chore

#228 feat: ability to add claims without proposals
  components/claim/claim-card.tsx
  hooks/useCustomToasts.ts
  lib/services/getPsycHolders.ts
  lib/services/getPsycHoldersNoProposals.ts
  lib/services/merkle.ts
  lib/services/voteCounter.test.ts
  lib/services/voteCounter.ts
  services/graph.ts
Labels: enhancement

#230 fix: get correct psyc holders
  lib/services/getPsycHolders.ts
  lib/services/getPsycHoldersNoProposals.ts
  lib/services/voteCounter.test.ts
  lib/services/voteCounter.ts
  services/graph.ts
Labels: bug

#233 update contracts
  constants/contracts.ts
Labels: chore

#199 Feat: move windows so that connect button is more visible on all screens
  components/nft-sale-widget/index.tsx
  components/shopify-widget/index.tsx
  components/windows/blog.tsx
  components/windows/claim.tsx
  components/windows/highlight.tsx
  components/windows/manifesto.tsx
  components/windows/radio.tsx
  components/windows/swap-widget.tsx
Labels: enhancement

#238 fix: improve error message phrasing
  hooks/useCustomToasts.ts
Labels: fix

#239 Develop
  hooks/useCustomToasts.ts
Labels: chore

#241 update mainnet contract addresses
  constants/contracts.ts
Labels: chore

#246 Develop
  services/graph.ts
Labels: fix

#247 temporary removal of copy sale functionality
  components/nft-sale-widget/common/sale-type-switch.tsx
  components/nft-sale-widget/layout/nft-sale/mint-psyc-header.tsx
  components/nft-sale-widget/layout/owned-nfts/owned-nft-item.tsx
  providers/SaleWidgetContext.tsx
Labels: chore

#248 temporarily remove copy sale functionality
  components/nft-sale-widget/common/sale-type-switch.tsx
  components/nft-sale-widget/layout/nft-sale/mint-psyc-header.tsx
  components/nft-sale-widget/layout/owned-nfts/owned-nft-item.tsx
  providers/SaleWidgetContext.tsx
Labels: chore

#249 fix: read tokens from contract on a timer
  components/windows/swap-widget.tsx
  pages/index.tsx
  services/web3/useReadTotalTokensForSale.tsx
Labels: enhancement

#250 Develop
  components/windows/swap-widget.tsx
  pages/index.tsx
  services/web3/useReadTotalTokensForSale.tsx
Labels: enhancement

#251 chore: make banner text responsive
  pages/index.tsx
Labels: chore

#253 feat: change default open windows and claims header
  components/claim/claimable-rewards.tsx
  components/windows/claim.tsx
  components/windows/swap-widget.tsx
  pages/index.tsx
Labels: enhancement

#252 Develop
  components/claim/claimable-rewards.tsx
  components/windows/claim.tsx
  components/windows/swap-widget.tsx
  pages/index.tsx
Labels: chore

#254 chore: close shopify widget
  components/shopify-widget/index.tsx
Labels: chore

#255 Develop
  components/shopify-widget/index.tsx
Labels: chore

#256 fix name
  components/claim/claimable-rewards.tsx
Labels: bug

#257 Develop
  components/claim/claimable-rewards.tsx
Labels: bug
