Repository LinumLabs/psydao-io, pull requests merged in 2024-10, with the labels that each got.

#174 Feat: add POAP logic
  .env.example
  components/shopify-widget/index.tsx
  components/ui/marquee.tsx
  config/env.mjs
  next-env.d.ts
  pages/api/poap.ts
  pages/api/shopify.ts
  pages/index.tsx
  utils/getPOAPStatus.ts
Labels: enhancement

#183 update eslint and imports
  .eslintrc.cjs
  eslint.config.mjs
  package.json
  yarn.lock
Labels: chore

#181 Wire up shopify
  components/shopify-widget/index.tsx
  config/env.mjs
  hooks/useCustomToasts.ts
  hooks/useRedirectToShopify.tsx
  pages/api/shopify.ts
  utils/createShopifyCart.ts
  utils/generateProductDiscount.ts
Labels: enhancement

#187 Chore: update config files
  .env.example
  eslint.config.mjs
Labels: chore

#180 Initial claim window
  components/claim/claim-card.tsx
  components/claim/dummyData.ts
  components/ui/menu.tsx
  components/windows/claim.tsx
  lib/types.ts
  pages/index.tsx
Labels: enhancement

#186 Feat: prevent multiple claims
  components/shopify-widget/index.tsx
  constants/shopifyWidget.ts
  pages/api/discount-usage.ts
  pages/api/poap.ts
  utils/createShopifyCart.ts
  utils/determineDiscountCodeUsage.ts
  utils/generateProductDiscount.ts
  utils/getAddressFromQuery.ts
Labels: enhancement

#188 Refactor: make api data less visible
  hooks/useRedirectToShopify.tsx
  pages/api/poap.ts
  pages/api/shopify.ts
  utils/getPOAPStatus.ts
Labels: chore

#189 clean up
  components/shopify-widget/index.tsx
  utils/determineDiscountCodeUsage.ts
Labels: chore

#190 Fix: improve feedback speed
  components/shopify-widget/index.tsx
  hooks/useGetUserOrders.tsx
  pages/api/discount-usage.ts
  pages/api/shopify-proxy.ts
  pages/index.tsx
  utils/apolloClient.ts
  utils/determineDiscountCodeUsage.ts
Labels: enhancement

#191 Fix: shopify widget overlap
  components/nft-sale-widget/index.tsx
  components/shopify-widget/index.tsx
  components/ui/menu.tsx
  components/windows/blog.tsx
  components/windows/claim.tsx
  components/windows/highlight.tsx
  components/windows/manifesto.tsx
  components/windows/swap-widget.tsx
  pages/index.tsx
Labels: enhancement

#192 Feat: add state toasts
  components/claim/create-reward-claim.tsx
  hooks/useCustomToasts.ts
  services/web3/useApprovePsy.tsx
  services/web3/useCreateNewClaimableBatch.tsx
  services/web3/useGetMinimumClaimDeadline.tsx
Labels: enhancement

#197 Feat: added claim toasts and loading state to claim section
  components/claim/claim-card.tsx
  components/claim/claimable-rewards.tsx
  hooks/useCustomToasts.ts
  hooks/useGetBatchClaims.ts
  services/web3/useClaim.tsx
Labels: enhancement

#203 fix claimed state casing issue
  lib/services/merkle.ts
Labels: bug

#201 improve toast func in batch creation
  components/claim/create-reward-claim.tsx
  hooks/useCustomToasts.ts
  services/web3/useApprovePsy.tsx
  services/web3/useCreateNewClaimableBatch.tsx
Labels: bug

#207 Fix: remove some duplication
  hooks/useGetUserOrders.tsx
  lib/services/psydaoSubgraph.ts
  lib/services/snapshotGraphQL.ts
  services/graph.ts
  utils/getMerkleProof.ts
Labels: chore

#209 improve merkle root files
  hooks/useFetchProof.ts
  services/getWhitelistMerkleProof.ts
  services/merkleRootProofs.ts
Labels: chore

#210 renamed service files to be more descriptive
  lib/services/firstProposalsApproved.ts
  lib/services/getPsycHolders.ts
  lib/services/getSnapshotProposalsAndVotes.ts
  lib/services/voteCounter.ts
Labels: chore

#211 fix: remove need for psyc-sg-url
  .env.example
  config/env.mjs
  config/graphqlClients.ts
  constants/claims.ts
Labels: chore

#216 improve fullscreen style claim window
  components/windows/claim.tsx
Labels: bug

#215 feat: some tweaks to claims
  .eslintrc.json
  components/windows/claim.tsx
  hooks/useGetBatchClaims.ts
  lib/services/config/test-mapping.ts
  lib/services/getPsycHolders.ts
  lib/services/voteCounter.test.ts
  lib/services/voteCounter.ts
  package.json
  providers/Web3Provider.tsx
  services/graph.ts
  vitest.config.ts
  yarn.lock
Labels: enhancement

#200 migrate backend functions
  .env.example
  .eslintrc.json
  components/claim/create-reward-claim.tsx
  components/windows/claim.tsx
  config/apolloClients.ts
  config/env.mjs
  config/graphql.ts
  config/graphqlClients.ts
  constants/claims.ts
  constants/shopifyWidget.ts
  hooks/useBuyNft.ts
  hooks/useCustomToasts.ts
  hooks/useFetchProof.ts
  hooks/useGetBatchClaims.ts
  hooks/useGetUserOrders.tsx
  lib/services/config/test-mapping.ts
  lib/services/firstProposalsApproved.ts
  lib/services/getPsycHolders.ts
  lib/services/getSnapshotProposalsAndVotes.ts
  lib/services/ipfs.ts
  lib/services/merkle.ts
  lib/services/voteCounter.test.ts
  lib/services/voteCounter.ts
  package.json
  pages/_app.tsx
  pages/api/distribution.ts
  pages/api/mapped-data.ts
  pages/index.tsx
  providers/Web3Provider.tsx
  services/getWhitelistMerkleProof.ts
  services/graph.ts
  services/merkleRootProofs.ts
  services/web3/useApprovePsy.tsx
  services/web3/useClaim.tsx
  services/web3/useCreateNewClaimableBatch.tsx
  services/web3/useNextBatchId.tsx
  utils/getMerkleProof.ts
  vitest.config.ts
  yarn.lock
Labels: enhancement

#217 remove duplicate client
  hooks/useGetUserOrders.tsx
  utils/apolloClient.ts
Labels: bug

#218 fix: re-add reset after claim
  components/claim/claim-card.tsx
Labels: bug

#219 fix:remove .eslintrc.json
  .eslintrc.json
Labels: bug

#220 Change set interval tanstack
  components/claim/admin-view-claims.tsx
  components/claim/claim-card.tsx
  components/claim/claimable-rewards.tsx
  hooks/useGetBatchClaims.ts
Labels: enhancement

#221 fix: update imports and remove redundant checks
  lib/services/ipfs.ts
  services/web3/useCreateNewClaimableBatch.tsx
  services/web3/useGetMinimumClaimDeadline.tsx
Labels: bug

#222 fix: make create claims work
  .env.example
  components/claim/admin-view-claims.tsx
  components/claim/create-reward-claim.tsx
  config/env.mjs
  config/graphqlClients.ts
  constants/claims.ts
  lib/server-utils.ts
  lib/services/getPsycHolders.ts
  lib/services/voteCounter.test.ts
  pages/api/distribution.ts
  services/graph.ts
  services/web3/useApprovePsy.tsx
  services/web3/useClaim.tsx
Labels: bug

#213 claims UI improvements
  components/claim/admin-view-claims.tsx
  components/claim/claim-button.tsx
  components/claim/claimable-rewards.tsx
  components/windows/claim.tsx
Labels: enhancement

#225 fix: claims formatting issue
  components/claim/claim-card.tsx
Labels: bug

#224 make correct states display on claim cards
  components/claim/claim-card.tsx
  components/claim/claimable-rewards.tsx
  lib/services/merkle.ts
  lib/types.ts
Labels: fix

#226 update contract addresses
  constants/contracts.ts
Labels: chore
