Repository LinumLabs/psydao-io, pull requests merged in 2025-01, with the labels that each got.

#288 feat(freebase): freebase updates
  components/freebase/README.md
  components/freebase/add-deposit-token.tsx
  components/freebase/index.tsx
  components/freebase/manage-reward-token.tsx
  components/freebase/pool-card.tsx
  constants/contracts.ts
  hooks/useFreebaseAdmin.tsx
  hooks/useFreebaseUser.tsx
  lib/services/freebase.ts
  services/freebase-graph.ts
Labels: enhancement

#289 feat(freebase): freebase admin rewards
  components/freebase/add-deposit-token.tsx
  components/freebase/set-allocation-point.tsx
  components/freebase/set-reward-per-block.tsx
  hooks/useFreebaseAdmin.tsx
  hooks/useFreebaseUser.tsx
  lib/services/freebase.ts
  services/freebase-graph.ts
  services/web3/useApproveToken.tsx
  services/web3/useGetTokenAllowance.tsx
Labels: enhancement

#285 feat: loading states for freebase admin rewards
  components/freebase/add-deposit-token.tsx
  components/freebase/admin-freebase-component.tsx
  components/freebase/manage-reward-token.tsx
  components/freebase/reward-configuration.tsx
  components/freebase/set-allocation-point.tsx
  components/freebase/set-reward-per-block.tsx
  components/freebase/token-management.tsx
  hooks/useFreebaseAdmin.tsx
Labels: enhancement

#294 fix(freebase): change conversion location for consistency
  hooks/useFreebaseAdmin.tsx
  services/web3/useApproveToken.tsx
Labels: fix

#290 fix(freebase): reward input values
  hooks/useCustomToasts.ts
  hooks/useFreebaseAdmin.tsx
  lib/services/freebase.ts
  services/web3/useApproveToken.tsx
Labels: bug

#291 feat(freebase): add poll interval to graph queries
  lib/services/freebase.ts
  services/freebase-graph.ts
Labels: enhancement

#293 feat(freebase): frontend user dashboard updates
  components/freebase/index.tsx
  components/freebase/pool-card.tsx
  hooks/useFreebaseUser.tsx
  lib/constants.ts
  lib/services/freebase.ts
  pages/_app.tsx
  services/freebase-graph.ts
Labels: enhancement

#295 Fix(freebase): UI improvements
  components/ui/menu.tsx
  components/windows/freebase.tsx
Labels: fix

#296 fix(freebase): fix reward per block contract value and display
  components/freebase/set-reward-per-block.tsx
  hooks/useFreebaseAdmin.tsx
Labels: fix

#298 chore(freebase): update sepolia contract address
  constants/contracts.ts
Labels: chore

#297 feat: show pending rewards on user cards
  components/freebase/pool-card.tsx
  hooks/useFreebaseUser.tsx
Labels: enhancement

#302 feat: make user section accessible for admins
  components/freebase/admin-freebase-component.tsx
  components/freebase/index.tsx
  components/windows/freebase.tsx
Labels: enhancement

#299 fix(freebase): allow deposit decimals
  components/freebase/pool-card.tsx
  hooks/useFreebaseUser.tsx
Labels: bug

#304 fix(freebase): fix wallet not connected state
  components/windows/freebase.tsx
Labels: fix

#303 Fix: ensure that approve and deposit happens in one step
  components/freebase/pool-card.tsx
  components/windows/freebase.tsx
  hooks/useFreebaseUser.tsx
Labels: fix

#305 chore(freebase): add freebase contract address to env
  config/env.mjs
  hooks/useFreebaseAdmin.tsx
  hooks/useFreebaseUser.tsx
Labels: chore

#310 fix: add decimals to reward token adding
  components/freebase/manage-reward-token.tsx
  components/freebase/token-management.tsx
  hooks/useFreebaseAdmin.tsx
Labels: bug

#314 Fix: made changes so that top up functionality works as expected
  .env.example
  abis/PsyDAOMasterBase.json
  components/freebase/manage-reward-token.tsx
  components/freebase/token-management.tsx
  constants/contracts.ts
  hooks/useFreebaseAdmin.tsx
Labels: fix

#315 chore(freebase): add new ABI and update contract address
  abis/PsyDAOMasterBase.json
  constants/contracts.ts
Labels: chore

#317 fix(freebase): improve loading states in admin section
  components/freebase/manage-reward-token.tsx
  hooks/useFreebaseAdmin.tsx
  hooks/useFreebaseUser.tsx
  services/web3/useApproveToken.tsx
Labels: fix

#318 chore(freebase): update contract address
  constants/contracts.ts
Labels: chore

#319 fix(freebase): display issue in pool 0
  hooks/useFreebaseUser.tsx
Labels: fix

#320 chore(freebase): migrate to using original subgraph
  .env.example
  components/freebase/README.md
  components/freebase/add-deposit-token.tsx
  config/apolloClients.ts
  config/env.mjs
  constants/contracts.ts
  hooks/useFreebaseUser.tsx
  lib/services/freebase.ts
  services/freebase-graph.ts
Labels: chore

#323 Added claim button
  components/freebase/pool-card.tsx
Labels: enhancement

#324 feat: add defined.fi integration and token price hook
  .env.example
  components/freebase/pool-card.tsx
  config/env.mjs
  hooks/useGetTokenPrice.tsx
  lib/services/freebase.ts
  package.json
  pages/api/defined.ts
  services/freebase-graph.ts
  yarn.lock
Labels: enhancement

#325 Feat: calculate APY
  components/freebase/pool-card.tsx
  config/env.mjs
  constants/apy.ts
  hooks/useGetApyDetails.tsx
  hooks/useGetMultiplier.tsx
  hooks/useGetTokenPrice.tsx
  hooks/useGetTotalAllocPoint.tsx
  lib/services/freebase.ts
  services/freebase-graph.ts
  utils/calculateApy.ts
Labels: enhancement

#326 feat: add tests for APY calculations
  lib/services/freebase.ts
  utils/calculateApy.test.ts
  utils/calculateApy.ts
Labels: enhancement

#327 Develop
  .env.example
  components/freebase/pool-card.tsx
  config/env.mjs
  constants/apy.ts
  hooks/useGetApyDetails.tsx
  hooks/useGetMultiplier.tsx
  hooks/useGetTokenPrice.tsx
  hooks/useGetTotalAllocPoint.tsx
  lib/services/freebase.ts
  package.json
  pages/api/defined.ts
  services/freebase-graph.ts
  utils/calculateApy.test.ts
  utils/calculateApy.ts
  yarn.lock
Labels: enhancement
